### ISSUE TITLE
Release checklist

### ISSUE THREAD

**Issue by christopher-dG** [PurgePJ/Discord.jl#8]
As of right now we tick [all the boxes](https://gist.github.com/meew0/bbbbd5348967dee5f7e84c0cd58983fd) for inclusion in the DAPI server, which also indicates that we're pretty close to being able to put out a first release :tada:.

Some things which still need to be done:

* [x] Fix #9
* [x] Audit log change keys (#1)
* [x] Use the cache for REST stuff, but also offer a means of not using the cache (probably a `Client` field)
* [x] Examples for all major feature sets (CRUD API, REST API, event handling, commands, sharding) (#2)
* [x] Summary docs ("Why Julia/Discord.jl?", CRUD API overview) (#2), add some of this to README
* [x] Tests: Anything not network-dependent should be tested
* [x] Take care of some `TODO`s (this is vague, not all of them are serious problems)
* [x] Multipart form-data: Handle file uploading.
* [x] Smarter caching: Things like guilds shouldn't be deleted, but messages, presences etc. should.
* [ ] HTTP.jl #348 merged + released
* [x] REST wrappers exported

Things which would be nice to have but aren't necessary:

* [ ] Detailed tutorials for a few common bot use cases, which use techniques from examples above (#2) (the current example should be reworked but for now we don't need much more)
* [ ] Command framework (`add_command!` is not terrible for now) 
* [ ] "Helper" functions to chain common ops (update: I think we can basically wait for feedback on this and implement things as they're desired)

We could find a lot of good ideas by looking around at other libraries, the JS and Python ones are probably a good place to start since they have the most users.

**Comment by PurgePJ** [comment]
Added multipart

**Comment by PurgePJ** [comment]
Only thing missing is waiting for the Pull Request, which is not needed since we have a fork of it.

**Comment by christopher-dG** [comment]
I'd rather not maintain that fork and I don't think that we can enforce people to actually use the fork over regular HTTP (you don't activate the manifests of your dependencies)

**Comment by PurgePJ** [comment]
HTTP.jl #348 has been merged.

**Comment by PurgePJ** [comment]
Will add soon another example showing off `do` syntax with events.

**Comment by christopher-dG** [comment]
Gonna close now, we know we just need to wait for HTTP.
